### ISSUE TITLE
Maybe you can help here

### ISSUE THREAD

**Issue by Stamimail** [jscher2000/userchrome-dot-org#1]
**IRC - Firefox community & support channel:**

10:22		*** BB joined #firefox

10:25	BB	Hi, sometimes I want to change the look of the browser to a view of a desktop window. How to do it?
10:27	Caspy7	BB: are you meaning on Android?

10:27	BB	No. To get a firefox window without the UI of firefox?

10:29	BB	*to have
10:30	BB	to remove/restore all the bars of Firefox with a hotkey

10:31	arai	for what do you need it for?

10:32	BB	Sometimes you need a litte window, and the bars take place.

10:33	arai	so... just general purpose?
10:34	BB	what do you mean general purpose?
10:34	arai	if you're looking for a solution for some specific purpose, there may be some workaround
10:34	mceier	F11 ?

10:35	BB	F11, is missing the title bar, and you cann't snapping it
10:36	BB	arai: can you give me ideas for what you mean

10:39	BB	Do you mean something like this?
10:39	BB	https://applicationize.me/now
10:40	BB	btw, this is chrome based. Is there a similar thing working with firefox?
10:41	arai	like, there was an extension that shows youtube video like Picture in Picture in other webpage
10:41	arai	(it was legacy extension, and won't work anymore tho
10:42	arai	so, if you have any specific purpose, we could look for some extension or somerthing
10:42	BB	Anyway, I tried the applicationize.me, but I want other solution. I want the ctrl+t and ctrl+N and Back/Forward to work

10:44	BB	OK, Ctrl+t won't fit to this
10:46	BB	OR, the it will fit, but the user will not see the tabs, and will use the ctrl+tab
10:48	BB	WOW, so there isn't a simple way to toggle the bars?

10:53	BB	Are there development commands that control the UI, Where can I find them?
10:54	arai	there may be some chance in userChrome.css, but you'll need to find a way to toggle (maybe with tricky selector etc)

**Comment by jscher2000** [comment]
Here are some example rules for bars. The tabs bar rule scrunches it down to a short height that shows the tops of the tabs, and if you hover in that 3px zone, the bar shows in full. The main toolbar rules hides it, but if you focus the address bar, that part will show.

    /* Squash tab bar to 3px unless a tab is hovered */
    #TabsToolbar, 
    #TabsToolbar .tabbrowser-tab {
      height: 29px !important; /* 29px compact, 33px normal, YMMV */
      min-height: 29px !important;
      max-height: 29px !important;
      transition: all 0.5s ease-in-out;
    } 
    #TabsToolbar:not(:hover), 
    #TabsToolbar:not(:hover) .tabbrowser-tab[selected] {
      height: 3px !important;
      min-height: 3px !important;
      max-height: 3px !important;
      transition: all 0.5s ease-in-out;
    }
    #TabsToolbar:not(:hover) .tabbrowser-tab[selected] .tab-content {
      display: none;
    }

    /* Hide main toolbar contents EXCEPT Address bar */
    #nav-bar toolbarbutton, #search-container, 
    #stop-reload-button {
      display: none !important;
    }
    #nav-bar {
      min-height: 0px !important;
    }
    /* Hide Address bar when NOT focused (e.g., F6) */
    #urlbar:not([focused]), #urlbar:not([focused]) * {
      min-height: 0 !important;
      max-height: 0 !important;
      padding: 0 !important;
      margin: 0 !important; 
      border: none !important;
    }

**Comment by Stamimail** [comment]
Hi,
Thank you for your reply.
I managed to apply the code you wrote,
but sorry for that I'm looking for other solution...
I'm trying to have a hotkey, to toggle between a Browser mode and a WebApp mode (getting a normal window with just the html document in it, without all the bars of firefox)
Do you think we can have such a hotkey for toggling (hide/unhide the firefox bars)?

**Comment by jscher2000** [comment]
CSS does not have a concept of hotkeys as far as I know.

**Comment by Stamimail** [comment]
Thank you.
