### ISSUE TITLE
userChrome-ShowAllHistoryAtTheTop stop working with Firefox 113

### ISSUE THREAD

**Issue by gabri25ele** [jscher2000/userchrome-dot-org#14]
the following css
https://www.userchrome.org/samples/userChrome-ShowAllHistoryAtTheTop.css 
stopped working with firefox 113

**Comment by jscher2000** [comment]
Sorry for the delay in picking up this question. Firefox 113 removed the properties starting with `-moz-box` so all rules containing those properties need to be updated.

Hopefully you found a fix by now but, if not, a great place to ask would be [r/FirefoxCSS](https://www.reddit.com/r/FirefoxCSS/) on Reddit.

**Comment by jscher2000** [comment]
Aha, looks like you already knew that.

https://www.reddit.com/r/FirefoxCSS/comments/13cl1k5/firefox_113_showallhistoryatthetop_not_work/
