### ISSUE TITLE
Active tab set to "connected" has bottom border 

### ISSUE THREAD

**Issue by cmvizitiu** [jscher2000/userchrome-dot-org#16]
Firefox 126.0 (64-bit) on Fedora Linux (KDE). 

For quite some time now (read: Firefox versions) the active tab has a thin line beneath it just like the other tabs making it difficult to spot as an active tab. 

![image](https://github.com/jscher2000/userchrome-dot-org/assets/19183476/cb9bdee1-efa0-41d4-bf63-ff299e5f3406)
&nbsp; 
&nbsp;  

I mean in previous versions, when tabs were connected the active tab used to look like this

![image](https://github.com/jscher2000/userchrome-dot-org/assets/19183476/cb479904-311b-4cdd-bf73-c7c5b75e8908)

&nbsp; 
&nbsp; 
It might sound like a tiny detail but for some reasons this small visual trick makes it very easy to spot the active tab.

**Comment by jscher2000** [comment]
Hmm, I don't have that line on the System or Light theme on Windows. Do you know whether it is a top border on the main toolbar, or something added to the tabs bar itself? To turn off any top border on the main toolbar, you could try this:

````
#nav-bar {
    --tabs-navbar-separator-style: none !important;
}
````

If it is a top border on the main toolbar, I don't see an obvious way to cover that up with a tab, but this could be because I don't _really_ understand `display: flex` styling.

**Comment by jscher2000** [comment]
In case the border is on top of the nav bar, or across the entire bottom of the tab bar, you could try this override:

````
/* BETA - Move border from top of nav bar to bottom of tab bar items */
#navigator-toolbox {
    /* Set border color for consistency (predefined var, fallback value) */
    --user-border-color: var(--chrome-content-separator-color, light-dark(rgb(204, 204, 204), hsl(240, 5%, 5%)));
    border-bottom: 0.01px solid var(--user-border-color) !important;
}
#nav-bar {
    border-top: none !important;
}
#TabsToolbar, #TabsToolbar > .toolbar-items, #TabsToolbar-customization-target {
    border-bottom: none !important;
}
#TabsToolbar toolbarbutton, .tabbrowser-tab:not(selected){
    border-bottom: 0.01px solid var(--user-border-color) !important;
}
````

**Comment by jscher2000** [comment]
The spacer is easy, but I have some gaps on the scroll buttons:

```
/* BETA - Move border from top of nav bar to bottom of tab bar items */
#navigator-toolbox {
    /* Set border color for consistency (predefined var, fallback value) */
    --user-border-color: var(--chrome-content-separator-color, light-dark(rgb(204, 204, 204), hsl(240, 5%, 5%)));
    border-bottom: 0.01px solid var(--user-border-color) !important;
}
#nav-bar {
    border-top: none !important;
}
#TabsToolbar, #TabsToolbar > .toolbar-items, #TabsToolbar-customization-target {
    border-bottom: none !important;
}
#TabsToolbar toolbarbutton, .tabbrowser-tab:not(selected), #TabsToolbar .titlebar-spacer,
#scrollbutton-up, #scrollbutton-down {
    border-bottom: 0.01px solid var(--user-border-color) !important;
}
```

Probably there's a better approach to this. You could try [r/FirefoxCSS](https://www.reddit.com/r/FirefoxCSS/).
