### ISSUE TITLE
Replace site icon with sound icon on tabs when playing audio?

### ISSUE THREAD

**Issue by loxia01** [jscher2000/userchrome-dot-org#3]
Hi, thanks for all your work on userchrome.org that makes Firefox better!

Is it possible to have the sound icon placed on the tab right side (to the left of the close icon) like in Firefox 78 (ESR)?  

Thanks in advance.

**Comment by jscher2000** [comment]
> Is it possible to have the sound icon placed on the tab right side (to the left of the close icon) like in Firefox 78 (ESR)?

I think I have seen something mentioned on [r/FirefoxCSS](https://www.reddit.com/r/FirefoxCSS/) but I don't have a link handy, unfortunately.

**Comment by loxia01** [comment]
Thanks for answering. I read a [reddit thread](https://www.reddit.com/r/FirefoxCSS/comments/nqyhcm/anyone_got_any_css_to_put_the_audible_icon_back/) about it and it seems extremely complicated (includes javascript and more). But I have decided I am happy with having the audio icon on the left side, right of the site icon.

I am closing this, thanks for your time.
